// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponFieldNames          = builder.RawFieldNames(&Coupon{})
	couponRows                = strings.Join(couponFieldNames, ",")
	couponRowsExpectAutoSet   = strings.Join(stringx.Remove(couponFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponRowsWithPlaceHolder = strings.Join(stringx.Remove(couponFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	couponModel interface {
		Insert(ctx context.Context, data *Coupon) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Coupon, error)
		Update(ctx context.Context, data *Coupon) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCouponModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Coupon struct {
		Id             int64     `db:"id"`              // 优惠券ID
		CouponName     string    `db:"coupon_name"`     // 优惠券名称
		DiscountAmount int64     `db:"discount_amount"` // 抵扣金额/积分
		NeedPoint      int64     `db:"need_point"`      // 兑换所需积分
		Stock          int64     `db:"stock"`           // 库存
		CreateTime     time.Time `db:"create_time"`     // 创建时间
	}
)

func newCouponModel(conn sqlx.SqlConn) *defaultCouponModel {
	return &defaultCouponModel{
		conn:  conn,
		table: "`coupon`",
	}
}

func (m *defaultCouponModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCouponModel) FindOne(ctx context.Context, id int64) (*Coupon, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponRows, m.table)
	var resp Coupon
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponModel) Insert(ctx context.Context, data *Coupon) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, couponRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CouponName, data.DiscountAmount, data.NeedPoint, data.Stock)
	return ret, err
}

func (m *defaultCouponModel) Update(ctx context.Context, data *Coupon) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CouponName, data.DiscountAmount, data.NeedPoint, data.Stock, data.Id)
	return err
}

func (m *defaultCouponModel) tableName() string {
	return m.table
}
