// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pointLogFieldNames          = builder.RawFieldNames(&PointLog{})
	pointLogRows                = strings.Join(pointLogFieldNames, ",")
	pointLogRowsExpectAutoSet   = strings.Join(stringx.Remove(pointLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	pointLogRowsWithPlaceHolder = strings.Join(stringx.Remove(pointLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	pointLogModel interface {
		Insert(ctx context.Context, data *PointLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PointLog, error)
		Update(ctx context.Context, data *PointLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPointLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PointLog struct {
		Id          int64     `db:"id"`           // 日志ID
		UserId      int64     `db:"user_id"`      // 用户ID
		ChangePoint int64     `db:"change_point"` // 变动积分（正数增加 负数减少）
		ChangeType  string    `db:"change_type"`  // 变动类型：里程入账/兑换优惠券/商品消费
		RelationId  int64     `db:"relation_id"`  // 关联ID（里程记录/优惠券/订单ID）
		CreateTime  time.Time `db:"create_time"`  // 创建时间
	}
)

func newPointLogModel(conn sqlx.SqlConn) *defaultPointLogModel {
	return &defaultPointLogModel{
		conn:  conn,
		table: "`point_log`",
	}
}

func (m *defaultPointLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPointLogModel) FindOne(ctx context.Context, id int64) (*PointLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pointLogRows, m.table)
	var resp PointLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPointLogModel) Insert(ctx context.Context, data *PointLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, pointLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ChangePoint, data.ChangeType, data.RelationId)
	return ret, err
}

func (m *defaultPointLogModel) Update(ctx context.Context, data *PointLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pointLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ChangePoint, data.ChangeType, data.RelationId, data.Id)
	return err
}

func (m *defaultPointLogModel) tableName() string {
	return m.table
}
