// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pointRuleFieldNames          = builder.RawFieldNames(&PointRule{})
	pointRuleRows                = strings.Join(pointRuleFieldNames, ",")
	pointRuleRowsExpectAutoSet   = strings.Join(stringx.Remove(pointRuleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	pointRuleRowsWithPlaceHolder = strings.Join(stringx.Remove(pointRuleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	pointRuleModel interface {
		Insert(ctx context.Context, data *PointRule) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PointRule, error)
		Update(ctx context.Context, data *PointRule) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPointRuleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PointRule struct {
		Id           int64     `db:"id"`             // 规则ID
		MilePerPoint int64     `db:"mile_per_point"` // 每多少公里
		PointValue   int64     `db:"point_value"`    // 对应积分
		IsDefault    int64     `db:"is_default"`     // 是否默认规则 1=是
		CreateTime   time.Time `db:"create_time"`    // 创建时间
	}
)

func newPointRuleModel(conn sqlx.SqlConn) *defaultPointRuleModel {
	return &defaultPointRuleModel{
		conn:  conn,
		table: "`point_rule`",
	}
}

func (m *defaultPointRuleModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPointRuleModel) FindOne(ctx context.Context, id int64) (*PointRule, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pointRuleRows, m.table)
	var resp PointRule
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPointRuleModel) Insert(ctx context.Context, data *PointRule) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, pointRuleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MilePerPoint, data.PointValue, data.IsDefault)
	return ret, err
}

func (m *defaultPointRuleModel) Update(ctx context.Context, data *PointRule) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pointRuleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MilePerPoint, data.PointValue, data.IsDefault, data.Id)
	return err
}

func (m *defaultPointRuleModel) tableName() string {
	return m.table
}
