// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	trafficRecordFieldNames          = builder.RawFieldNames(&TrafficRecord{})
	trafficRecordRows                = strings.Join(trafficRecordFieldNames, ",")
	trafficRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(trafficRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	trafficRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(trafficRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	trafficRecordModel interface {
		Insert(ctx context.Context, data *TrafficRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TrafficRecord, error)
		Update(ctx context.Context, data *TrafficRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTrafficRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TrafficRecord struct {
		Id          int64     `db:"id"`           // 记录ID
		UserId      int64     `db:"user_id"`      // 用户ID
		PlateNumber string    `db:"plate_number"` // 车牌
		Mileage     float64   `db:"mileage"`      // 行驶里程(公里)
		TrafficTime time.Time `db:"traffic_time"` // 通行时间
		IsCalculate int64     `db:"is_calculate"` // 是否核算积分 0=未核算 1=已核算
		CreateTime  time.Time `db:"create_time"`  // 创建时间
	}
)

func newTrafficRecordModel(conn sqlx.SqlConn) *defaultTrafficRecordModel {
	return &defaultTrafficRecordModel{
		conn:  conn,
		table: "`traffic_record`",
	}
}

func (m *defaultTrafficRecordModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTrafficRecordModel) FindOne(ctx context.Context, id int64) (*TrafficRecord, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", trafficRecordRows, m.table)
	var resp TrafficRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTrafficRecordModel) Insert(ctx context.Context, data *TrafficRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, trafficRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.PlateNumber, data.Mileage, data.TrafficTime, data.IsCalculate)
	return ret, err
}

func (m *defaultTrafficRecordModel) Update(ctx context.Context, data *TrafficRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, trafficRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.PlateNumber, data.Mileage, data.TrafficTime, data.IsCalculate, data.Id)
	return err
}

func (m *defaultTrafficRecordModel) tableName() string {
	return m.table
}
