// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userPointFieldNames          = builder.RawFieldNames(&UserPoint{})
	userPointRows                = strings.Join(userPointFieldNames, ",")
	userPointRowsExpectAutoSet   = strings.Join(stringx.Remove(userPointFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userPointRowsWithPlaceHolder = strings.Join(stringx.Remove(userPointFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userPointModel interface {
		Insert(ctx context.Context, data *UserPoint) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserPoint, error)
		FindOneByUserId(ctx context.Context, userId int64) (*UserPoint, error)
		Update(ctx context.Context, data *UserPoint) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserPointModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserPoint struct {
		Id         int64     `db:"id"`          // ID
		UserId     int64     `db:"user_id"`     // 用户ID
		TotalPoint int64     `db:"total_point"` // 总积分余额
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newUserPointModel(conn sqlx.SqlConn) *defaultUserPointModel {
	return &defaultUserPointModel{
		conn:  conn,
		table: "`user_point`",
	}
}

func (m *defaultUserPointModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserPointModel) FindOne(ctx context.Context, id int64) (*UserPoint, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userPointRows, m.table)
	var resp UserPoint
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPointModel) FindOneByUserId(ctx context.Context, userId int64) (*UserPoint, error) {
	var resp UserPoint
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userPointRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPointModel) Insert(ctx context.Context, data *UserPoint) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userPointRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TotalPoint)
	return ret, err
}

func (m *defaultUserPointModel) Update(ctx context.Context, newData *UserPoint) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userPointRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.TotalPoint, newData.Id)
	return err
}

func (m *defaultUserPointModel) tableName() string {
	return m.table
}
