// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userCouponFieldNames          = builder.RawFieldNames(&UserCoupon{})
	userCouponRows                = strings.Join(userCouponFieldNames, ",")
	userCouponRowsExpectAutoSet   = strings.Join(stringx.Remove(userCouponFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userCouponRowsWithPlaceHolder = strings.Join(stringx.Remove(userCouponFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userCouponModel interface {
		Insert(ctx context.Context, data *UserCoupon) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserCoupon, error)
		Update(ctx context.Context, data *UserCoupon) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserCouponModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserCoupon struct {
		Id           int64        `db:"id"`            // ID
		UserId       int64        `db:"user_id"`       // 用户ID
		CouponId     int64        `db:"coupon_id"`     // 优惠券ID
		Status       int64        `db:"status"`        // 状态 0=未使用 1=已使用 2=已过期
		ExchangeTime time.Time    `db:"exchange_time"` // 兑换时间
		UseTime      sql.NullTime `db:"use_time"`      // 使用时间
	}
)

func newUserCouponModel(conn sqlx.SqlConn) *defaultUserCouponModel {
	return &defaultUserCouponModel{
		conn:  conn,
		table: "`user_coupon`",
	}
}

func (m *defaultUserCouponModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserCouponModel) FindOne(ctx context.Context, id int64) (*UserCoupon, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userCouponRows, m.table)
	var resp UserCoupon
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserCouponModel) Insert(ctx context.Context, data *UserCoupon) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userCouponRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.CouponId, data.Status, data.ExchangeTime, data.UseTime)
	return ret, err
}

func (m *defaultUserCouponModel) Update(ctx context.Context, data *UserCoupon) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userCouponRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.CouponId, data.Status, data.ExchangeTime, data.UseTime, data.Id)
	return err
}

func (m *defaultUserCouponModel) tableName() string {
	return m.table
}
