// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddTrafficReq struct {
	UserId      int64   `json:"userId"`
	PlateNumber string  `json:"plateNumber"`
	Amount      float64 `json:"amount"`      // 消费金额(元)
	TrafficTime string  `json:"trafficTime"` // 消费时间
}

type CalculatePointReq struct {
	UserId int64 `json:"userId"`
}

type CalculatePointResp struct {
	Response
	CalculatedPoints int `json:"calculatedPoints"`
}

type CouponInfo struct {
	Id             int64  `json:"id"`
	CouponName     string `json:"couponName"`
	DiscountAmount int    `json:"discountAmount"`
	NeedPoint      int    `json:"needPoint"`
	Stock          int    `json:"stock"`
	CreateTime     string `json:"createTime"`
}

type CouponListResp struct {
	Response
	List []CouponInfo `json:"list"`
}

type CreateOrderReq struct {
	UserId  int64 `json:"userId"`
	GoodsId int64 `json:"goodsId"`
}

type CreateOrderResp struct {
	Response
	OrderId         int64  `json:"orderId"`
	OrderNo         string `json:"orderNo"`
	UsePoint        int    `json:"usePoint"`
	RemainingPoints int    `json:"remainingPoints"`
}

type ExchangeCouponReq struct {
	UserId   int64 `json:"userId"`
	CouponId int64 `json:"couponId"`
}

type ExchangeCouponResp struct {
	Response
	RemainingPoints int `json:"remainingPoints"`
}

type GoodsInfo struct {
	Id         int64  `json:"id"`
	GoodsName  string `json:"goodsName"`
	NeedPoint  int    `json:"needPoint"`
	Stock      int    `json:"stock"`
	CreateTime string `json:"createTime"`
}

type GoodsListResp struct {
	Response
	List []GoodsInfo `json:"list"`
}

type OrderInfo struct {
	Id         int64  `json:"id"`
	OrderNo    string `json:"orderNo"`
	UserId     int64  `json:"userId"`
	GoodsName  string `json:"goodsName"`
	CouponName string `json:"couponName"`
	UsePoint   int    `json:"usePoint"`
	CreateTime string `json:"createTime"`
}

type OrderListResp struct {
	Response
	List []OrderInfo `json:"list"`
}

type PointBalanceResp struct {
	Response
	TotalPoint int64 `json:"totalPoint"`
}

type PointLog struct {
	Id          int64  `json:"id"`
	UserId      int64  `json:"userId"`
	ChangePoint int64  `json:"changePoint"`
	ChangeType  string `json:"changeType"`
	RelationId  int64  `json:"relationId"`
	CreateTime  string `json:"createTime"`
}

type PointLogsResp struct {
	Response
	List []PointLog `json:"list"`
}

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type TrafficListResp struct {
	Response
	List []TrafficRecord `json:"list"`
}

type TrafficRecord struct {
	Id          int64   `json:"id"`
	UserId      int64   `json:"userId"`
	PlateNumber string  `json:"plateNumber"`
	Amount      float64 `json:"amount"`      // 消费金额(元)
	TrafficTime string  `json:"trafficTime"` // 消费时间
	IsCalculate int     `json:"isCalculate"`
	CreateTime  string  `json:"createTime"`
}

type UserCoupon struct {
	Id           int64  `json:"id"`
	CouponName   string `json:"couponName"`
	Status       int    `json:"status"`
	ExchangeTime string `json:"exchangeTime"`
	UseTime      string `json:"useTime"`
}

type UserCouponListResp struct {
	Response
	List []UserCoupon `json:"list"`
}

type UserIdReq struct {
	UserId int64 `form:"userId"` // 改为查询参数
}

type UserInfo struct {
	Id          int64  `json:"id"`
	UserName    string `json:"userName"`
	Phone       string `json:"phone"`
	PlateNumber string `json:"plateNumber"`
	CreateTime  string `json:"createTime"`
}

type UserInfoResp struct {
	Response
	UserInfo
}

type UserListResp struct {
	Response
	List []UserInfo `json:"list"`
}
