// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	coupon "jhb-api/api/internal/handler/coupon"
	goods "jhb-api/api/internal/handler/goods"
	order "jhb-api/api/internal/handler/order"
	point "jhb-api/api/internal/handler/point"
	traffic "jhb-api/api/internal/handler/traffic"
	user "jhb-api/api/internal/handler/user"
	"jhb-api/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 兑换优惠券
				Method:  http.MethodPost,
				Path:    "/exchange",
				Handler: coupon.ExchangeCouponHandler(serverCtx),
			},
			{
				// 获取优惠券列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: coupon.GetCouponListHandler(serverCtx),
			},
			{
				// 获取我的优惠券
				Method:  http.MethodGet,
				Path:    "/my",
				Handler: coupon.GetUserCouponsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/coupon"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取商品列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: goods.GetGoodsListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/goods"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建订单
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				// 获取订单列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: order.GetOrderListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取积分余额
				Method:  http.MethodGet,
				Path:    "/balance",
				Handler: point.GetPointBalanceHandler(serverCtx),
			},
			{
				// 积分核算
				Method:  http.MethodPost,
				Path:    "/calculate",
				Handler: point.CalculatePointHandler(serverCtx),
			},
			{
				// 获取积分日志
				Method:  http.MethodGet,
				Path:    "/logs",
				Handler: point.GetPointLogsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/point"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 添加里程记录
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: traffic.AddTrafficHandler(serverCtx),
			},
			{
				// 获取里程列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: traffic.GetTrafficListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/traffic"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				// 初始化用户
				Method:  http.MethodPost,
				Path:    "/init",
				Handler: user.InitUsersHandler(serverCtx),
			},
			{
				// 获取用户列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: user.GetUserListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
